# This workflow will do a clean install of node dependencies, run tests and send coverage to Code Climate.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coverage

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: 276bf9cbd926f0f9f4e3a74ff080e0c6707753187fae13b22f076e8e64464ae9
      with:
        coverageCommand: npm run test:coverage
